const problemDB = [
    // ===============================================
    // 2025 고졸 2차 수학
    // ===============================================
    { id: 1, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "1. 두 다항식 A=2x²+5, B=x²-4x에 대하여 A+B는?", options: ["3x²-4x+5", "3x²+4x-5", "3x²-x+5", "3x²+x-5"], answer: 0, explanation: "동류항끼리 더하면 (2x²+x²) - 4x + 5 = 3x²-4x+5 입니다." },
    { id: 2, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "2. 등식 ax²+x=4x²+bx가 x에 대한 항등식일 때, 두 상수 a, b에 대하여 a-b의 값은?", options: ["0", "1", "2", "3"], answer: 3, explanation: "항등식이므로 계수가 같아야 합니다. a=4, b=1이므로 a-b = 3입니다." },
    { id: 3, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "3. 다항식 x³-2x²+5를 x-1로 나누었을 때, 나머지는?", options: ["1", "2", "4", "8"], answer: 2, explanation: "나머지 정리에 의해 x에 1을 대입하면 1-2+5 = 4입니다." },
    { id: 4, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "4. 다항식 x³-3x²+3x-1을 인수분해한 식이 (x-a)³일 때, 상수 a의 값은?", options: ["1", "2", "3", "4"], answer: 0, explanation: "(x-1)³ = x³-3x²+3x-1 이므로 a=1입니다." },
    { id: 5, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "5. 복소수 3-4i의 켤레복소수가 a+bi일 때, 두 실수 a, b에 대하여 a+b의 값은?", options: ["1", "4", "7", "10"], answer: 2, explanation: "켤레복소수는 허수부의 부호만 반대입니다. 3+4i이므로 3+4=7입니다." },
    { id: 6, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "6. 이차방정식 x²+2x+3=0의 근에 대한 설명으로 옳은 것은?", options: ["한 근은 x=-4이다.", "두 근의 합은 1이다.", "두 근의 곱은 3이다.", "중근을 갖는다."], answer: 2, explanation: "근과 계수의 관계에 의해 두 근의 곱은 c/a = 3/1 = 3입니다." },
    { id: 7, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "images/2025_2_Math_07.png", question: "7. 1≤x≤3일 때, 이차함수 y=-(x-3)²+6의 최솟값은?", options: ["1", "2", "3", "4"], answer: 1, explanation: "x=1일 때 y=-4+6=2이므로 최솟값은 2입니다." },
    { id: 8, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "8. 연립방정식 x+y=5, xy=a의 해가 x=3, y=b일 때, a+b의 값은?", options: ["1", "4", "6", "8"], answer: 3, explanation: "x=3이면 y=2(b=2)입니다. a=xy=6입니다. a+b=8." },
    { id: 9, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "images/2025_2_Math_09.png", question: "9. 그림은 부등식 |x-1|≤4의 해를 수직선 위에 나타낸 것이다. 상수 a의 값은?", options: ["1", "2", "3", "5"], answer: 3, explanation: "-4 ≤ x-1 ≤ 4 이므로 -3 ≤ x ≤ 5 입니다." },
    { id: 10, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "images/2025_2_Math_10.png", question: "10. 수직선 위의 두 점 A(1), B(8)에 대하여 선분 AB를 4:3으로 내분하는 점 P의 좌표는?", options: ["3", "4", "5", "6"], answer: 2, explanation: "내분점 공식: (4*8 + 3*1) / (4+3) = 35/7 = 5." },
    { id: 11, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "11. 직선 y=-x+2에 수직이고 점 (0,5)를 지나는 직선의 방정식은?", options: ["y=x+5", "y=x+7", "y=-x+5", "y=-x+7"], answer: 0, explanation: "수직이려면 기울기 곱이 -1이어야 하므로 기울기는 1입니다. y절편이 5이므로 y=x+5." },
    { id: 12, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "images/2025_2_Math_12.png", question: "12. 중심의 좌표가 (3,3)이고 x축과 y축에 동시에 접하는 원의 방정식은?", options: ["(x+3)²+(y+3)²=3", "(x+3)²+(y-3)²=3", "(x-3)²+(y+3)²=9", "(x-3)²+(y-3)²=9"], answer: 3, explanation: "중심이 (3,3)이므로 (x-3)²+(y-3)²=r² 형태입니다." },
    { id: 13, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "images/2025_2_Math_13.png", question: "13. 좌표평면 위의 점 (-1, -4)를 x축에 대하여 대칭이동한 점의 좌표는?", options: ["(1, 4)", "(-1, -4)", "(-1, 4)", "(-4, -1)"], answer: 2, explanation: "x축 대칭은 y좌표의 부호가 바뀝니다. (-1, 4)" },
    { id: 14, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "14. 집합인 것을 <보기>에서 고른 것은? (보기: ㄴ.자연수, ㄹ.10~20 홀수)", options: ["ㄱ, ㄷ", "ㄱ, ㄹ", "ㄴ, ㄷ", "ㄴ, ㄹ"], answer: 3, explanation: "기준이 명확해야 집합입니다. 자연수와 홀수는 명확합니다." },
    { id: 15, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "15. 두 집합 A={2, 4, a+1}, B={a-3, 4, 6}에 대하여 A=B일 때, 상수 a의 값은?", options: ["1", "3", "5", "7"], answer: 2, explanation: "A와 B가 같으려면 원소가 같아야 합니다. a+1=6 이므로 a=5." },
    { id: 16, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "", question: "16. 명제 'x=1이면 x⁴=1이다'의 역은?", options: ["x⁴=1이면 x=1이다.", "x⁴=1이면 x≠1이다.", "x=1이면 x⁴≠1이다.", "x≠1이면 x⁴≠1이다."], answer: 0, explanation: "'p이면 q이다'의 역은 'q이면 p이다'입니다." },
    { id: 17, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "images/2025_2_Math_17.png", question: "17. 함수 f:X→Y가 그림과 같을 때, f⁻¹(a)의 값은?", options: ["1", "2", "3", "4"], answer: 1, explanation: "역함수는 화살표를 거꾸로 따라갑니다. a에서 출발하면 2에 도착합니다." },
    { id: 18, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "images/2025_2_Math_18.png", question: "18. 무리함수 y=√(x-3)+b의 그래프는 시작점이 (3,5)이다. a+b는?", options: ["5", "8", "11", "14"], answer: 1, explanation: "시작점이 (3,5)이므로 y좌표 이동 b=5, 식에서 a=3에 해당(평행이동). a+b=3+5=8." },
    { id: 19, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "images/2025_2_Math_19.png", question: "19. 5개의 프로그램 중 서로 다른 2개를 택하여 순서대로 체험하는 경우의 수는?", options: ["12", "16", "20", "24"], answer: 2, explanation: "순서가 있으므로 순열 5P2 = 5 x 4 = 20." },
    { id: 20, year: "2025", round: "2", level: "고졸", subject: "수학", passage: "", image: "images/2025_2_Math_20.png", question: "20. 4종류의 잡곡 중 서로 다른 2종류를 선택하는 경우의 수는?", options: ["6", "7", "8", "9"], answer: 0, explanation: "순서 상관없이 선택이므로 조합 4C2 = (4x3)/2 = 6." },
// ===============================================
    // [한국사] 1번 ~ 25번
    // ===============================================
    {
        id: 401,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "1. 다음 중 (    )에 들어갈 유물로 옳은 것은?<br>< 신석기 시대의 생활 ><br>○ 생활 모습: 농경과 목축의 시작, 정착 생활<br>○ 대표 유물: 가락바퀴, (    )",
        options: ["상감청자", "호우명 그릇", "빗살무늬 토기", "불국사 3층 석탑"],
        answer: 2,
        explanation: "신석기 시대의 대표적인 유물은 빗살무늬 토기입니다."
    },
    {
        id: 402,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "2. 다음 설명에 해당하는 책은?<br>○ 일연이 민간에서 전승되는 자료를 수집하여 지은 책이다.<br>○ 단군 신화, 전설, 향가, 불교 관련 내용 등이 수록되어 있다.",
        options: ["동의보감", "목민심서", "삼국유사", "조선책략"],
        answer: 2,
        explanation: "일연이 쓴 책으로 단군 신화가 실려 있는 것은 삼국유사입니다."
    },
    {
        id: 403,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "3. 다음 중 (가)에 들어갈 사건으로 옳은 것은?<br><table class='w-full text-sm text-left text-gray-500 border'><thead><tr class='bg-gray-50'><th class='p-2 border'>시기</th><th class='p-2 border'>국가</th><th class='p-2 border'>역사적 사건</th></tr></thead><tbody><tr><td class='p-2 border'>4세기</td><td class='p-2 border'>백제</td><td class='p-2 border'>근초고왕이 마한을 복속하였다.</td></tr><tr><td class='p-2 border'>5세기</td><td class='p-2 border'>고구려</td><td class='p-2 border'><b>( 가 )</b></td></tr><tr><td class='p-2 border'>6세기</td><td class='p-2 border'>신라</td><td class='p-2 border'>진흥왕이 한강 유역을 차지하였다.</td></tr></tbody></table>",
        options: ["광해군이 대동법을 시행하였다.", "장수왕이 평양으로 천도하였다.", "정조가 탕평 정책을 실시하였다.", "공민왕이 반원 정책을 추진하였다."],
        answer: 1,
        explanation: "5세기 고구려의 전성기 때 장수왕은 남진 정책을 위해 평양으로 천도했습니다."
    },
    {
        id: 404,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "4. 다음 설명에 해당하는 제도는?<br>군포는 농민에게 큰 부담이었다. 조선 영조는 농민이 부담하는 군포를 1필로 줄여 주었고, 부족한 재정 수입은 결작, 선무군관포 등을 내게 하여 보충하였다.",
        options: ["균역법", "산림령", "합영법", "신문지법"],
        answer: 0,
        explanation: "영조가 군포 부담을 줄여주기 위해 실시한 제도는 균역법입니다."
    },
    {
        id: 405,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "5. 고려 광종의 정책으로 옳은 것을 <보기>에서 고른 것은?<br><보기><br>ㄱ. 과거제 시행<br>ㄴ. 척화비 건립<br>ㄷ. 훈민정음 창제<br>ㄹ. 노비안검법 실시",
        options: ["ㄱ, ㄴ", "ㄱ, ㄹ", "ㄴ, ㄷ", "ㄷ, ㄹ"],
        answer: 1,
        explanation: "고려 광종은 왕권 강화를 위해 과거제(ㄱ)와 노비안검법(ㄹ)을 실시했습니다."
    },
    {
        id: 406,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "6. 다음 설명에 해당하는 인물은?",
        image: "images/2025_2_Kor_06.png", // 👈 인물 카드 사진 추가
        // 텍스트 내용은 이미지에 있을 테니 passage는 비워두거나, 시각 장애인 접근성을 위해 남겨둬도 됩니다.
        passage: "<b>[한국사 인물 카드]</b><br>○ 불교 대중화에 힘씀<br>○ 화쟁 사상을 주장함<br>○ 「대승기신론소」를 저술함",
        options: ["김구", "원효", "김옥균", "전태일"],
        answer: 1,
        explanation: "불교 대중화와 화쟁 사상은 원효 대사의 업적입니다."
    },
    {
        id: 407,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "7. 다음 설명에 해당하는 사건은?<br>이 조형물은 1907년에 대구에서 시작된 (    )을 기념하는 것이다. (    )은 국민들이 성금을 모아 대한 제국의 국채 1,300만 원을 갚고 국권을 회복하자는 운동이다.",
        options: ["형평 운동", "브나로드 운동", "백제 부흥 운동", "국채 보상 운동"],
        answer: 3,
        explanation: "나랏빚을 갚자는 운동은 국채 보상 운동입니다."
    },
    {
        id: 408,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "8. 다음 (    )에 들어갈 사건으로 옳은 것은?<br>[답사 계획서]<br>○ 주제: 흔적을 따라가 보는 여행<br>○ 답사 장소 및 역사적 사건<br>- 한산도: 이순신의 한산도 대첩<br>- 진주: 김시민의 진주 대첩<br>⬇<br>관련 사건: (    )",
        options: ["을미사변", "임진왜란", "살수 대첩", "청산리 전투"],
        answer: 1,
        explanation: "이순신, 한산도 대첩, 김시민 등은 임진왜란과 관련된 내용입니다."
    },
    {
        id: 409,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "9. 다음 설명에 해당하는 사건은?<br>○ 1866년에 흥선 대원군의 천주교 박해를 구실로 프랑스 군대가 강화도를 침입함.<br>○ 양헌수가 이끄는 조선군이 정족산성에서 프랑스군을 물리침.",
        options: ["병인양요", "정읍 발언", "만적의 난", "매소성 전투"],
        answer: 0,
        explanation: "프랑스군이 강화도에 침입한 사건은 병인양요입니다."
    },
    {
        id: 410,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "10. 다음 (    )에 들어갈 내용으로 옳은 것은?<br>[한국사 신문]<br>통리기무아문에서 개화 정책을 추진하다!<br>강화도 조약 체결 이후 정부는 개화 업무를 총괄할 기구로 통리기무아문을 설치하여 개화 정책을 추진하였는데, 국방력 강화를 위해서 (    ).",
        options: ["동북 9성을 쌓았다", "경복궁을 중건하였다", "강동 6주를 설치하였다", "신식 군대인 별기군을 창설하였다"],
        answer: 3,
        explanation: "개화 정책의 일환으로 창설된 신식 군대는 별기군입니다."
    },
    {
        id: 411,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "11. 다음 내용에 해당하는 사건은?<br>농민군이 황토현과 황룡촌 전투에서 승리하고 전주성을 점령하자 정부는 농민군과 전주 화약을 체결하였다. 이후 농민군은 전라도 50여 개 군현에 집강소를 설치하여 각종 개혁을 실천하였다.",
        options: ["나·당 전쟁", "한·일 협정", "동학 농민 운동", "광주 학생 항일 운동"],
        answer: 2,
        explanation: "황토현 전투, 전주 화약, 집강소는 동학 농민 운동에 대한 설명입니다."
    },
    {
        id: 412,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "12. 다음 (    )에 들어갈 내용으로 옳은 것은?<br>< 1910년대 일제의 식민 통치 ><br>○ 헌병 경찰제 시행<br>○ (    ) 실시<br>○ 회사령 공포",
        options: ["영정법", "호포제", "토지 조사 사업", "유신 헌법"],
        answer: 2,
        explanation: "1910년대 일제의 대표적인 경제 수탈 정책은 토지 조사 사업입니다."
    },
    {
        id: 413,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "13. 다음 중 (    )에 들어갈 운동으로 옳은 것은?",
        image: "images/2025_2_Kor_13.png", // 👈 조형물 사진 추가
        passage: "이 조형물은 1907년에 대구에서 시작된 <b>(    )</b>을 기념하는 것이다. <b>(    )</b>은 국민들이 성금을 모아 대한 제국의 국채 1,300만 원을 갚고 국권을 회복하자는 운동이다.",
        options: ["을사의병", "아관파천", "새마을 운동", "국채 보상 운동"], // ⚠️ 13번 보기로 수정됨
        answer: 3,
        explanation: "나랏빚을 갚자는 운동은 국채 보상 운동입니다."
    },
    {
        id: 414,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "14. 다음 (    )에 들어갈 사건으로 옳은 것은?<br>1928년 라이징 선 석유 회사에서 일본인 감독이 한국인 노동자를 구타한 사건이 계기가 되어, 1929년 (    )이 일어났다. 국내는 물론이고 국외 노동 단체까지 지지를 보내왔지만 일제의 탄압으로 실패하였다.",
        options: ["광무개혁", "귀주 대첩", "원산 총파업", "위화도 회군"],
        answer: 2,
        explanation: "1929년 원산에서 일어난 최대 규모의 노동 운동은 원산 총파업입니다."
    },
    {
        id: 415,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "15. 다음 질문에 대한 답으로 옳은 것은?<br>\"1896년 서재필이 정부의 지원을 받아 창간한 것입니다. 한글판과 영문판으로 발행하여 국민을 계몽하고 국내 사정을 외국인에게도 알리려고 하였습니다. 이것은 무엇일까요?\"",
        options: ["독립신문", "경국대전", "삼국사기", "독서삼품과"],
        answer: 0,
        explanation: "서재필이 창간한 최초의 민간 신문은 독립신문입니다."
    },
    {
        id: 416,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "16. 다음 중 밑줄 친 '이 운동'에 해당하는 것은?<br>1920년 평양에서 조만식 등의 주도로 시작되어, 전국으로 확산되었다. 이 운동은 '내 살림 내 것으로', '조선 사람 조선 것' 등의 구호를 앞세우며 민족 산업의 보호와 육성을 위해 토산품 애용, 근검저축 등을 주장하였다.",
        options: ["교조 신원 운동", "물산 장려 운동", "6.10 만세 운동", "고구려 부흥 운동"],
        answer: 1,
        explanation: "국산품 애용 운동은 물산 장려 운동입니다."
    },
    {
        id: 417,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "17. 다음 (    )에 들어갈 내용으로 옳은 것은?<br>[한국사 묻고 답하기]<br>학생: 3·1운동을 계기로 일어난 변화에 대해 알려 주세요.<br>교사: 일제의 통치 방식이 '문화 통치'로 바뀌게 되었고, (    ).",
        options: ["비변사의 기능이 확대되었습니다", "대한민국 임시 정부가 수립되었습니다", "도병마사가 도평의사사로 개편되었습니다", "관료전이 지급되고 녹읍이 폐지되었습니다"],
        answer: 1,
        explanation: "3·1 운동의 결과로 독립 운동을 체계적으로 이끌기 위해 대한민국 임시 정부가 수립되었습니다."
    },
    {
        id: 418,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "18. 다음 (    )에 들어갈 법으로 옳은 것은?<br>중·일 전쟁을 일으킨 일제는 1938년에 전쟁 수행을 위하여 (    )을 제정하고 이를 한반도에도 적용하였다. 이후 일제는 이 법에 근거하여 국민 징용령 등 각종 통제 법령을 공포하고, 전시 동원 체제를 강화하였다.",
        options: ["과전법", "진대법", "노비종모법", "국가 총동원법"],
        answer: 3,
        explanation: "1938년 일제가 인력과 물자를 수탈하기 위해 제정한 법은 국가 총동원법입니다."
    },
    {
        id: 419,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "19. 다음 (    )에 들어갈 지역으로 옳은 것은?<br>가: 안용복은 일본에 건너가 (    )가 조선의 영토임을 확인하였어.<br>나: 그래. 대한 제국은 「칙령 제41호」를 통해 (    )를 울도군의 관할로 두었어.",
        options: ["독도", "진도", "강화도", "제주도"],
        answer: 0,
        explanation: "안용복과 대한 제국 칙령 제41호는 독도와 관련된 내용입니다."
    },
    {
        id: 420,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "20. 다음 (    )에 들어갈 사건으로 옳은 것은?<br>[학습 주제: (    )]<br>- 개최 시기 및 장소: 1943년, 이집트<br>- 참여국: 미국, 영국, 중국<br>- 목적: 제2차 세계 대전 전후 처리 논의<br>- 내용: '적당한 시기'에 한국의 독립 약속",
        options: ["한성 조약", "화백 회의", "카이로 회담", "남북 적십자 회담"],
        answer: 2,
        explanation: "한국의 독립을 최초로 약속한 국제 회담은 카이로 회담입니다."
    },
    {
        id: 421,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "21. 다음 설명에 해당하는 전쟁은?<br>1950년 북한군이 남침을 감행하였고 낙동강 일대까지 진출하였다. 이에 맥아더 유엔군 총사령관은 인천 상륙 작전을 감행하여 전세를 역전시켰다. 이후 1.4 후퇴를 거쳐 38도선 일대에서 공방전이 지속되다가 1953년 정전 협정이 체결되었다.",
        options: ["신미양요", "정묘호란", "6·25 전쟁", "봉오동 전투"],
        answer: 2,
        explanation: "1950년 발발하여 인천 상륙 작전, 정전 협정이 있었던 전쟁은 6·25 전쟁입니다."
    },
    {
        id: 422,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "22. 다음 (    )에 들어갈 내용으로 옳은 것은?<br>< 반민족 행위자 처벌을 위한 노력 ><br>제헌 국회는 반민족 행위 처벌법을 제정하고, 이를 근거로 반민족 행위 특별 조사 위원회(반민특위)를 조직하였다. 반민 특위는 1949년 1월부터 각종 자료, 증언 등을 바탕으로 (    ).",
        options: ["국자감을 설치하였다", "친일파를 검거하였다", "현량과를 실시하였다", "조선의용대를 조직하였다"],
        answer: 1,
        explanation: "반민특위의 목적은 친일파(반민족 행위자)를 처벌하는 것이었습니다."
    },
    {
        id: 423,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "23. 다음 설명에 해당하는 것은?<br>박정희 정부는 1967년부터 1971년까지 기간산업을 육성하여 산업 구조를 개편하고 사회 간접 자본의 확충에 주력하였다. 이 시기에 경부 고속 도로가 개통되었고 포항 제철을 짓기 시작하였으며 경제가 급속히 성장하였다.",
        options: ["만민공동회", "산미 증식 계획", "제1차 미·소 공동 위원회", "제2차 경제 개발 5개년 계획"],
        answer: 3,
        explanation: "1960~70년대 박정희 정부의 경제 성장 정책은 경제 개발 5개년 계획입니다."
    },
    {
        id: 424,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "24. 다음 설명에 해당하는 사건은?<br>1980년 신군부의 계엄령 확대와 휴교령에 반대하여 광주에서 시위가 일어났다. 광주의 학생과 시민들은 '광주 시민 궐기문'을 발표하고 격렬하게 저항하였다.",
        options: ["예송 논쟁", "기벌포 전투", "홍경래의 난", "5.18 민주화 운동"],
        answer: 3,
        explanation: "1980년 광주에서 신군부에 저항한 운동은 5.18 민주화 운동입니다."
    },
    {
        id: 425,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "한국사",
        question: "25. 다음 (    )에 들어갈 정부로 옳은 것은?<br>가: (    ) 시기에 있었던 사건에 대해 발표해 보세요.<br>나: 분단 이후 처음으로 남북 정상 회담이 개최되었습니다.<br>다: 외환 위기 극복을 위해 금모으기 운동 등이 전개되었습니다.",
        options: ["장면 정부", "김대중 정부", "이명박 정부", "이승만 정부"],
        answer: 1,
        explanation: "최초의 남북 정상 회담과 금모으기 운동은 김대중 정부 시기의 일입니다."
    },

// ===============================================
    // [영어] 1번 ~ 25번 (수정완료)
    // ===============================================
    {
        id: 101,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "1. 다음 중 밑줄 친 부분의 뜻으로 가장 적절한 것은?<br>We need to find a <u>balance</u> between work and family life.",
        options: ["감정", "균형", "모험", "학습"],
        answer: 1,
        explanation: "balance는 '균형'이라는 뜻입니다. 일과 가정 생활 사이의 균형을 찾아야 한다는 내용입니다."
    },
    {
        id: 102,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "2. 다음 중 밑줄 친 부분의 뜻으로 가장 적절한 것은?<br>A: I accidentally broke the classroom window.<br>B: Oh, no! Did you tell the teacher?<br>A: Yes, I told her what happened and apologized.<br>B: Good. <u>Honesty is the best policy.</u>",
        options: ["정직이 최선의 방책이다.", "진정한 배움에는 지름길이 없다.", "시간은 화살처럼 빨리 지나간다.", "일찍 일어나는 새가 벌레를 잡는다."],
        answer: 0,
        explanation: "'Honesty is the best policy'는 '정직이 최선의 방책이다'라는 속담입니다."
    },
    {
        id: 103,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "3. 다음 중 밑줄 친 부분의 뜻으로 가장 적절한 것은?<br>Please <u>throw away</u> the trash after the picnic.",
        options: ["버리다", "들여놓다", "보관하다", "판매하다"],
        answer: 0,
        explanation: "throw away는 '버리다'라는 뜻입니다."
    },
    {
        id: 104,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "4. 다음 중 밑줄 친 두 단어의 의미 관계와 다른 것은?<br>The gift made me <u>happy</u>, but I became <u>sad</u> when I lost it.",
        options: ["slow - fast", "wide - narrow", "equal - same", "easy - difficult"],
        answer: 2,
        explanation: "happy와 sad는 반의어 관계입니다. equal(동등한)과 same(같은)은 유의어 관계이므로 정답은 3번입니다."
    },
    {
        id: 105,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "5. 다음 안내문에서 언급되지 않은 것은?",
        image: "images/2025_2_Eng_05.png",
        passage: "<b>Mud Fun Day</b><br>Date: August 16th<br>Place: Riverside Park<br>Activities: mud slides, mud fights<br>* Make sure to bring a change of clothes.",
        options: ["행사 날짜", "행사 장소", "활동 내용", "참가 연령"],
        answer: 3,
        explanation: "날짜(8월 16일), 장소(강변 공원), 활동(머드 슬라이드 등)은 언급되었으나 참가 연령은 나와있지 않습니다."
    },
    {
        id: 106,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "6. 다음 중 빈칸에 공통으로 들어갈 말로 가장 적절한 것은?<br>He goes for a (    ) every morning to stay healthy.<br>She wants to (    ) her own shop someday.",
        options: ["run", "hand", "will", "lose"],
        answer: 0,
        explanation: "go for a run(달리러 가다), run a shop(가게를 운영하다)에 공통으로 들어갈 단어는 run입니다."
    },
    {
        id: 107,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "7. 다음 중 빈칸에 공통으로 들어갈 말로 가장 적절한 것은?<br>He told her the reason (    ) he was crying.<br>Can you tell me (    ) you were absent?",
        options: ["how", "why", "where", "which"],
        answer: 1,
        explanation: "the reason 뒤에 오며, 이유를 묻는 표현에 쓰이는 관계부사는 why입니다."
    },
    {
        id: 108,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "8. 다음 중 빈칸에 공통으로 들어갈 말로 가장 적절한 것은?<br>I'm really looking forward (    ) going camping.<br>My mom used (    ) read books to me when I was little.",
        options: ["as", "to", "for", "like"],
        answer: 1,
        explanation: "look forward to(~를 고대하다), used to(~하곤 했다)에 공통으로 들어갈 전치사는 to입니다."
    },
    {
        id: 109,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "9. 다음 대화에서 밑줄 친 표현의 의미로 가장 적절한 것은?<br>I studied hard, <u>so</u> I passed the test.",
        options: ["게다가", "그래서", "반면에", "사실상"],
        answer: 1,
        explanation: "so는 인과관계를 나타내는 접속사로 '그래서'라는 뜻입니다."
    },
    {
        id: 110,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "10. 다음 대화에서 알 수 있는 A의 심정으로 가장 적절한 것은?<br>A: I just heard that I won the writing contest!<br>B: That's great. I knew you could do it.<br>A: I still can't believe it. I'm so delighted!",
        options: ["기쁨", "불만", "실망", "평온"],
        answer: 0,
        explanation: "글짓기 대회에서 우승해서 delighted(기쁜)라고 했으므로 기쁨이 정답입니다."
    },
    {
        id: 111,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "11. 다음 대화가 이루어지는 장소로 가장 적절한 것은?<br>A: Hi, can I get a slice of cheese pizza and a coke?<br>B: Sure. Would you like anything else?<br>A: No, that's all. Do you accept credit cards?",
        options: ["경찰서", "미용실", "소방서", "음식점"],
        answer: 3,
        explanation: "피자와 콜라를 주문하고 계산하는 상황이므로 음식점입니다."
    },
    {
        id: 112,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "12. 다음 글에서 밑줄 친 It이 가리키는 것으로 가장 적절한 것은?<br>Jungle World is back! We are very pleased to announce this program. <u>It</u> will be held during the month of September.",
        options: ["plant", "animal", "program", "visitor"],
        answer: 2,
        explanation: "It은 앞 문장의 this program(Jungle World)을 가리킵니다."
    },
    {
        id: 113,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "13. 다음 대화의 빈칸에 들어갈 말로 가장 적절한 것은?<br>A: Tomorrow is my sister's birthday.<br>B: Did you buy a present for her?<br>A: Yes. I bought this hat.<br>B: (        )<br>A: Oh, it's beautiful. She will like it.",
        options: ["Where do you live", "When is your birthday", "Why did you buy it", "What do you think of it"],
        answer: 3,
        explanation: "모자를 샀다고 보여준 후, B가 '아름답다'고 대답했으므로, 빈칸에는 의견을 묻는 'What do you think of it?'이 적절합니다."
    },
    {
        id: 114,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "14. 다음 대화의 빈칸에 들어갈 말로 가장 적절한 것은?<br>A: Where did you leave your umbrella?<br>B: (        )",
        options: ["I think I left it on the bus", "I can explain why he liked it", "I helped my friend make lunch", "I bought a new dress yesterday"],
        answer: 0,
        explanation: "우산을 어디에 두었냐는 질문(Where)에는 장소를 답하는 1번(버스에 두고 온 것 같아)이 적절합니다."
    },
    {
        id: 115,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "15. 다음 대화의 주제로 가장 적절한 것은?<br>A: Can you tell me how to make a comic book?<br>B: First, you have to choose a topic, and then write a short story.<br>A: I see. Do you draw the pictures afterwards?<br>B: That's right.",
        options: ["도서관 이용 규칙", "만화책을 만드는 방법", "좋아하는 영화 장르", "이야기를 경청하는 태도"],
        answer: 1,
        explanation: "만화책을 만드는 방법(how to make a comic book)에 대해 묻고 답하고 있습니다."
    },
    {
        id: 116,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "16. 다음 글을 쓴 목적으로 가장 적절한 것은?<br>The school writing club is holding a weekly workshop... If you are interested in becoming a more confident writer, join us on Thursdays in room 205.",
        options: ["안부를 전하려고", "예약을 승인하려고", "참가자를 모집하려고", "행사 취소를 공지하려고"],
        answer: 2,
        explanation: "글쓰기 클럽 워크숍에 관심 있는 학생들을 모집(join us)하는 글입니다."
    },
    {
        id: 117,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "17. 다음 수영장 안내문의 내용과 일치하지 않는 것은?",
        image: "images/2025_2_Eng_17.png",
        passage: "<b>Swimming Pool Information</b><br>Location: 9th floor<br>Operating hours: 6:00 a.m. ~ 10:00 p.m.<br>Free for all hotel guests<br>* Drinks can be purchased at the pool.",
        options: ["9층에 위치해 있다.", "오전 6시부터 오후 10시까지 운영한다.", "수영모를 착용해야 한다.", "음료는 판매하지 않는다."],
        answer: 3,
        explanation: "안내문에 'Drinks can be purchased(음료 구매 가능)'라고 되어 있으므로 4번은 일치하지 않습니다. (수영모 착용은 'Must wear a swimming cap'이라고 본문에 있습니다.)"
    },
    {
        id: 118,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "18. 다음 The Friendly Market에 대한 설명과 일치하지 않는 것은?<br>The Friendly Market opens near City Hall... Anyone who comes to the market can get a free face painting. The market is held on Sundays...",
        options: ["시청 근처에서 열린다.", "유기농 간식이 판매된다.", "페이스 페인팅은 무료이다.", "일요일은 휴무일이다."],
        answer: 3,
        explanation: "The market is held on Sundays(일요일에 열림)라고 했으므로 일요일 휴무는 틀린 내용입니다."
    },
    {
        id: 119,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "19. 다음 글의 주제로 가장 적절한 것은?<br>Do you ever feel like you can't control your anger? Here are some tips for you. First, take a deep breath... Second, count to ten...",
        options: ["미래에 유망한 직업", "예술 작품 창조 과정", "분노를 조절하는 방법", "기후 변화가 가속화하는 이유"],
        answer: 2,
        explanation: "화를 조절하는 팁(control your anger)에 대해 설명하고 있습니다."
    },
    {
        id: 120,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "20. 다음 글의 빈칸에 들어갈 말로 가장 적절한 것은?<br>Upcycling can turn old items into something new... By reusing used objects for different purposes, you can (    ) trash.",
        options: ["order", "teach", "reduce", "punish"],
        answer: 2,
        explanation: "업사이클링을 통해 쓰레기를 줄일 수 있다(reduce)는 내용이 적절합니다."
    },
    {
        id: 121,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "21. 다음 글의 빈칸에 들어갈 말로 가장 적절한 것은?<br>Many countries are facing a problem with low birth rates... Thus, countries are trying to (    ) policies that will help increase birth rates.",
        options: ["cut", "stop", "forget", "develop"],
        answer: 3,
        explanation: "출산율을 높이기 위한 정책을 개발(develop)하려고 노력한다는 흐름이 적절합니다."
    },
    {
        id: 122,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "22. 글의 흐름으로 보아 다음 문장이 들어가기에 가장 적절한 곳은?<br><b>[There, some sea animals eat this waste.]</b><br><br>Plastic is a useful material but can be harmful to the environment. ( ① ) Plastic waste takes decades to break down... ( ② ) Moreover, plastic waste is often washed out to the ocean. ( ③ ) Eventually these animals may end up on our dinner table. ( ④ )",
        options: ["①", "②", "③", "④"],
        answer: 2,
        explanation: "'There'는 앞 문장의 'ocean'을 가리키고, 뒤이어 이 동물들이 식탁에 오른다는 내용이 나오므로 ③번 위치가 적절합니다."
    },
    {
        id: 123,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        question: "23. 다음 글의 바로 뒤에 이어질 내용으로 가장 적절한 것은?<br>Marathons are exciting events... However, there are several types of injuries people can get when they run a marathon.",
        options: ["마라톤으로 인한 부상의 유형", "마라톤 경기 규칙의 변천사", "육상 선수를 위한 식단", "정신 건강의 중요성"],
        answer: 0,
        explanation: "글의 마지막에 '마라톤을 할 때 입을 수 있는 여러 가지 부상'을 언급했으므로, 뒤에는 부상의 유형이 이어져야 합니다."
    },
   {
        id: 124,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        passage: "<b>[24~25] 다음 글을 읽고 물음에 답하시오.</b><br><br>Everyone feels stress sometimes, especially when life gets busy. But too much stress can lead to various problems such as sleeplessness and anxiety. In order to (    ) stress from harming your life, you need to manage it well. Stress management is the key to your well-being in the modern world.",
        question: "24. 윗글의 빈칸에 들어갈 말로 가장 적절한 것은?",
        options: ["feed", "raise", "collect", "prevent"],
        answer: 3,
        explanation: "스트레스가 삶을 해치는 것을 막기 위해(prevent A from B) 관리해야 한다는 내용입니다."
    },
    {
        id: 125,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "영어",
        passage: "<b>[24~25] 다음 글을 읽고 물음에 답하시오.</b><br><br>Everyone feels stress sometimes, especially when life gets busy. But too much stress can lead to various problems such as sleeplessness and anxiety. In order to (    ) stress from harming your life, you need to manage it well. Stress management is the key to your well-being in the modern world.",
        question: "25. 윗글의 주제로 가장 적절한 것은?",
        options: ["스트레스 관리의 중요성", "봉사 활동의 중요성", "수면 부족의 위험성", "다양한 운동 방법"],
        answer: 0,
        explanation: "현대 사회에서 스트레스 관리가 중요하다는 것이 글의 주제입니다."
    },
// ===============================================
    // [도덕] 1번 ~ 25번
    // ===============================================
    {
        id: 501,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "1. 다음의 문제를 다루는 실천 윤리 분야로 가장 적절한 것은?<br>• 사생활 침해<br>• 저작권 침해<br>• 사이버 폭력<br>• 해킹과 바이러스 유포",
        options: ["정보 윤리", "생명 윤리", "평화 윤리", "환경 윤리"],
        answer: 0,
        explanation: "사이버 공간에서 발생하는 문제들을 다루는 것은 정보 윤리입니다."
    },
    {
        id: 502,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "2. 다음 퀴즈에 대한 정답으로 옳은 것은?<br>Q. 대승 불교가 제시한 이상적 인간으로, 위로는 진리를 구하고 아래로는 중생을 구제하여 자비를 실천하는 사람을 일컫는 말은 무엇일까요?",
        options: ["군자", "보살", "진인", "대장부"],
        answer: 1,
        explanation: "대승 불교의 이상적 인간상은 보살입니다. 군자/대장부는 유교, 진인은 도가 사상입니다."
    },
    {
        id: 503,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "3. (    )에 들어갈 용어로 가장 적절한 것은?<br>주제: (    ) 윤리학<br>특징: 도덕 언어의 논리적 타당성과 의미 분석을 주된 목표로 함.<br>주요 물음: '좋음'과 '옳음'이라는 용어의 의미는 무엇인가?",
        options: ["기술", "규범", "메타", "신경"],
        answer: 2,
        explanation: "도덕 언어의 의미와 논리적 타당성을 분석하는 학문은 메타 윤리학입니다."
    },
    {
        id: 504,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "4. 유교 사상의 특징으로 옳은 것을 <보기>에서 고른 것은?<br><보기><br>ㄱ. 좌망, 심재의 수양 방법을 강조한다.<br>ㄴ. 대동 사회를 이상 사회로 제시한다.<br>ㄷ. 누구나 불성(佛性)을 지니고 태어난다고 본다.<br>ㄹ. 성인(聖人), 군자를 이상적 인간상으로 제시한다.",
        options: ["ㄱ, ㄴ", "ㄱ, ㄷ", "ㄴ, ㄹ", "ㄷ, ㄹ"],
        answer: 2,
        explanation: "유교 사상은 대동 사회(ㄴ)와 성인/군자(ㄹ)를 강조합니다. ㄱ은 도가, ㄷ은 불교 사상입니다."
    },
    {
        id: 505,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "5. 다음에서 소개하는 윤리 사상가는?",
        passage: "<b>◆ 도덕 인물 카드 ◆</b><br>• 의무론을 대표하는 윤리 사상가<br>• 도덕 법칙은 정언 명령의 형식으로 제시된다고 주장함<br>• 선의지에서 비롯된 행위만이 도덕적 가치를 지닌다고 봄",
        options: ["밀", "칸트", "홉스", "테일러"],
        answer: 1,
        explanation: "의무론, 정언 명령, 선의지를 강조한 사상가는 칸트입니다."
    },
    {
        id: 506,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "6. 교사의 질문에 적절하지 않은 대답을 한 학생은?",
        passage: "<b>교사: 평화 통일을 위한 노력에 어떤 것이 있을까요?</b><br>학생1: 남북한의 교류·협력을 활성화해야 합니다.<br>학생2: 남북한이 상호 존중의 태도를 지녀야 합니다.<br>학생3: 군사적 안보를 포기하고 남북한 대화를 단절해야 합니다.<br>학생4: 사회적·문화적 편견을 해소하기 위해 노력해야 합니다.",
        options: ["학생1", "학생2", "학생3", "학생4"],
        answer: 2,
        explanation: "군사적 안보를 튼튼히 하면서 대화를 지속해야 합니다. 학생3의 대답은 적절하지 않습니다."
    },
    {
        id: 507,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "7. 다음 설명에 해당하는 노직(Nozick, R.)의 정의의 원칙은?<br>취득 및 양도의 과정에서 부정의로 인해 현재의 소유 상태가 발생하였다면 바로잡아야 한다.",
        options: ["교정의 원칙", "이전의 원칙", "자유의 원칙", "차등의 원칙"],
        answer: 0,
        explanation: "잘못된 소유 과정을 바로잡는 것은 교정의 원칙입니다."
    },
    {
        id: 508,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "8. (가)에 들어갈 용어로 가장 적절한 것은?<br>• 돌봄, 공감, 책임, 타인과의 관계 등을 중시<br>• 상황과 특수성을 고려한 윤리적 판단 강조<br>• 대표 인물: 길리건(Gilligan, C.), 나딩스(Noddings, N.)<br>⬇<br><b>( 가 )</b>",
        options: ["의무론", "덕 윤리", "공리주의", "배려 윤리"],
        answer: 3,
        explanation: "관계와 돌봄, 공감을 중시하는 사상은 배려 윤리입니다."
    },
    {
        id: 509,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "9. 시민 불복종의 정당화 조건을 <보기>에서 고른 것은?<br><보기><br>ㄱ. 공개적으로 해야 한다.<br>ㄴ. 최후의 수단이어야 한다.<br>ㄷ. 법 체계 전체에 항거해야 한다.<br>ㄹ. 사적 이익 추구만을 목적으로 해야 한다.",
        options: ["ㄱ, ㄴ", "ㄱ, ㄷ", "ㄴ, ㄹ", "ㄷ, ㄹ"],
        answer: 0,
        explanation: "시민 불복종은 공개적(ㄱ)이고 최후의 수단(ㄴ)이어야 합니다. 법 체계 전체를 부정하는 것이 아니며(ㄷ 틀림), 공익을 목적으로 해야 합니다(ㄹ 틀림)."
    },
    {
        id: 510,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "10. 다음 설명에 해당하는 자연관으로 가장 적절한 것은?<br>○ 특징: 모든 생명체가 도덕적 지위를 지닌다는 입장<br>○ 사상가: 슈바이처(Schweitzer, A.), 테일러(Taylor, P.) 등<br>○ 한계점: 생태계 전체를 도덕적으로 고려하지 못함",
        options: ["인간 중심주의", "동물 중심주의", "생명 중심주의", "생태 중심주의"],
        answer: 2,
        explanation: "모든 생명체의 가치를 존중하는 입장은 생명 중심주의입니다."
    },
    {
        id: 511,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "11. (가), (나)에 들어갈 내용으로 적절하지 않은 것은?<br>[토론 주제: 뇌사를 죽음으로 인정해야 한다]<br>• 찬성 입장 근거: ( 가 )<br>• 반대 입장 근거: ( 나 )",
        options: ["(가): 의료 자원을 효율적으로 사용할 수 있다.", "(가): 다른 환자의 생명을 구하거나 질병을 치료할 수 있다.", "(나): 뇌사 판정의 오류로 인해 인간 존엄성이 훼손될 수 있다.", "(나): 장기적인 연명 치료로 인한 가족의 부담을 줄일 수 있다."],
        answer: 3,
        explanation: "가족의 부담을 줄일 수 있다는 것은 '찬성 입장'의 근거로 쓰입니다. 반대 입장의 근거로는 적절하지 않습니다."
    },
    {
        id: 512,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "12. 다음 설명에 해당하는 용어는?<br>성 자체를 매매하거나 소비 욕구를 자극하는 데 이용하는 등 성을 상업적 수단으로 취급하는 행위",
        options: ["성교육", "성 역할", "양성평등", "성 상품화"],
        answer: 3,
        explanation: "성을 상업적 수단으로 이용하는 것은 성 상품화입니다."
    },
    {
        id: 513,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "13. (    )에 들어갈 용어로 가장 적절한 것은?<br>레건(Regan, T.)에 따르면, 일부 동물은 자신의 삶을 영위할 수 있는 능력, 즉 믿음, 욕구, 자각 등을 가진 (    )이므로 인간처럼 본래적 가치를 지닌다.",
        options: ["삶의 주체", "기계적 존재", "수단적 존재", "이성적 주체"],
        answer: 0,
        explanation: "레건은 일부 동물들이 믿음, 욕구 등을 지닌 '삶의 주체'라고 주장했습니다."
    },
    {
        id: 514,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "14. 공리주의 사상가인 벤담(Bentham, J.)의 입장에서 A, B에 들어갈 대답으로 옳게 짝 지어진 것은?<br>Q1: 모든 쾌락은 양적으로 계산할 수 있는가? -> A<br>Q2: 최대 다수의 최대 행복의 원리를 따라야 하는가? -> B",
        options: ["A: 예, B: 예", "A: 예, B: 아니요", "A: 아니요, B: 예", "A: 아니요, B: 아니요"],
        answer: 0,
        explanation: "벤담은 양적 공리주의자로 쾌락의 계산이 가능하다고 보았으며(예), 최대 다수의 최대 행복을 주장했습니다(예)."
    },
    {
        id: 515,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "15. 하버마스의 '담론 윤리'에 대한 학생의 답안 채점 결과로 (    )에 들어갈 점수는? (각 1점)<br>[질문 / 학생 답]<br>1. 자유로운 비판을 허용해야 하는가? / 예 (O)<br>2. 대화에의 참여는 평등해야 하는가? / 아니요 (X)<br>3. 의사소통의 과정은 합리적이어야 하는가? / 예 (O)",
        options: ["0점", "1점", "2점", "3점"],
        answer: 2,
        explanation: "하버마스는 대화 참여의 평등성을 강조합니다. 학생은 2번에서 틀렸으므로 2점입니다."
    },
    {
        id: 516,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "16. 다음 중 윤리적 성찰이 필요한 이유로 적절하지 않은 것은?",
        options: ["올바른 가치관과 인격을 형성하기 위해서이다.", "자신의 잘못을 반성하고 되풀이하지 않기 위해서이다.", "유행이나 사회적 분위기에 동조하며 살기 위해서이다.", "더 나은 삶을 위해 삶의 의미를 재정립하기 위해서이다."],
        answer: 2,
        explanation: "무비판적으로 유행이나 분위기에 휩쓸려 사는 것은 윤리적 성찰의 태도가 아닙니다."
    },
    {
        id: 517,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "17. 다음 중 장자의 죽음에 대한 관점으로 옳은 것은?",
        options: ["자신이 쌓은 업에 따라 윤회하는 과정이다.", "사계절의 운행과 같은 자연스러운 과정이다.", "영원불변한 이데아의 세계로 들어가는 과정이다.", "신의 명령에 따라 천국이나 지옥으로 가는 과정이다."],
        answer: 1,
        explanation: "장자는 죽음을 밤과 낮, 사계절의 변화와 같은 자연스러운 과정으로 보았습니다."
    },
    {
        id: 518,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "18. 국제 관계를 바라보는 (가), (나)의 관점이 옳게 짝 지어진 것은?<br>(가): 국가는 자국의 이익을 추구하고 국제 관계는 국가 간 힘의 논리에 따라 움직인다.<br>(나): 국제법이나 국제 규범으로 제도를 개선하여 국제 평화를 실현할 수 있다.",
        options: ["(가) 현실주의, (나) 자본주의", "(가) 사회주의, (나) 이상주의", "(가) 사회주의, (나) 자본주의", "(가) 현실주의, (나) 이상주의"],
        answer: 3,
        explanation: "(가)는 힘의 논리를 강조하는 현실주의, (나)는 제도와 규범을 강조하는 이상주의입니다."
    },
    {
        id: 519,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "19. 다음 설명에 해당하는 용어는?<br>다양한 채소와 과일이 그 특성을 유지하며 저마다의 맛을 내듯이 다양한 문화가 대등하게 조화를 이루어야 한다.",
        options: ["동화주의", "샐러드 볼 모형", "국수 대접 모형", "자문화 중심주의"],
        answer: 1,
        explanation: "각 문화의 고유성을 유지하며 조화를 이루는 모델은 샐러드 볼 모형입니다."
    },
    {
        id: 520,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "20. (    )에 들어갈 내용으로 가장 적절한 것은?<br>순자: 각자 자신의 이름에 걸맞게 직분을 수행해야 한다.<br>공자: 사람들이 자기 직분을 충실히 수행한다면 천하가 태평해진다.<br>공통점: 두 사상가 모두 직업을 통한 (    )을/를 강조한다.",
        options: ["무위자연", "역성혁명", "민주주의 실현", "사회적 역할 분담"],
        answer: 3,
        explanation: "유교 사상가들은 각자 맡은 바 직분(사회적 역할)을 충실히 수행하는 정명 사상을 강조했습니다."
    },
    {
        id: 521,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "21. 다음 중 사회 갈등 해결을 위한 자세로 적절하지 않은 것은?",
        options: ["갈등은 나쁜 것이므로 무조건 회피한다.", "다양성의 가치를 존중하고 대화에 임한다.", "상호 소통을 할 수 있는 합리적 절차를 중시한다.", "다른 것을 틀린 것으로 인식하는 태도에서 벗어난다."],
        answer: 0,
        explanation: "갈등을 무조건 회피하는 것은 근본적인 해결책이 아닙니다."
    },
    {
        id: 522,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "22. 다음 설명에 해당하는 사상가는?<br>사회 계약에 기초하여 살인자를 정당한 사회 구성원이 아니라고 간주하고, 사회 방위론의 입장에서 사형제를 찬성함.",
        options: ["갈퉁", "루소", "요나스", "베카리아"],
        answer: 1,
        explanation: "살인자를 사회 계약 파괴자로 보고 사형을 옹호한 사상가는 루소입니다."
    },
    {
        id: 523,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "23. (    )에 들어갈 내용으로 가장 적절한 것은?<br>A: 예술의 목적은 도덕이 아닌 미적 가치 구현에 있습니다.<br>B: 아닙니다. 예술은 도덕과 깊은 관련이 있습니다. 따라서 (    ).",
        options: ["예술은 윤리적 평가에서 자유로워야 합니다.", "예술은 올바른 품성 함양에 도움이 되어야 합니다.", "예술에 대한 어떠한 규제와 간섭도 반대해야 합니다.", "예술이 반드시 사회적 모순을 지적할 필요는 없습니다."],
        answer: 1,
        explanation: "B는 도덕주의 입장이므로 예술이 도덕적 교훈이나 품성 함양에 기여해야 한다고 주장합니다."
    },
    {
        id: 524,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "24. 다음 설명에 해당하는 개념은?<br>소비자가 도덕적 신념과 가치 판단에 따라 환경, 인권 등 각종 사회 문제에 접근하여 상품을 소비하는 행위",
        options: ["과시적 소비", "충동적 소비", "윤리적 소비", "합리적 소비"],
        answer: 2,
        explanation: "도덕적 가치를 고려하여 소비하는 행위는 윤리적 소비입니다."
    },
    {
        id: 525,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "도덕",
        question: "25. 다음 학생 답안의 밑줄 친 부분 중 옳지 않은 것은?<br>문제: 현대 환경 문제의 특징을 서술하시오.<br>답안: 오늘날 환경 문제는 <u>(1)국경을 초월하는 전 지구적 문제이다.</u> 따라서 <u>(2)책임 소재를 명확히 가리기 어려운 측면이 있으며</u>, <u>(3)인류의 생존을 위협하기도 한다.</u> 그러나 <u>(4)모든 환경 문제는 일시적으로 발생하기 때문에 쉽게 회복이 가능하다.</u>",
        options: ["(1)", "(2)", "(3)", "(4)"],
        answer: 3,
        explanation: "현대 환경 문제는 장기간 지속되며 회복이 어렵거나 불가능한 경우가 많습니다."
    },
// ===============================================
    // [사회] 1번 ~ 25번
    // ===============================================
    {
        id: 301,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "1. 다음 (    )에 들어갈 내용으로 가장 적절한 것은?<br>• 시민이 주권을 가지고 국가를 스스로 다스려야 한다는 이념을 ( ㉠ ) (이)라고 하며, 시민의 정치적 참여를 보장하는 것은 행복한 삶의 조건이다.<br>• 인간이 자리 잡고 살아갈 수 있는 주거지와 주변 환경을 ( ㉡ ) (이)라고 하며, 쾌적한 자연환경과 안락한 주거 환경은 행복한 삶의 조건이다.",
        options: ["㉠: 민주주의, ㉡: 정주 환경", "㉠: 민주주의, ㉡: 도덕적 실천", "㉠: 경제적 안정, ㉡: 정주 환경", "㉠: 경제적 안정, ㉡: 도덕적 실천"],
        answer: 0,
        explanation: "시민의 주권과 참여는 '민주주의', 인간이 살아가는 주거지와 환경은 '정주 환경'입니다."
    },
    {
        id: 302,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "2. 다음에 해당하는 지역의 기후로 옳은 것은?<br>○ 분포: 적도를 중심으로 하는 저위도 지역<br>○ 전통 가옥: 개방적이고 지붕의 경사가 급한 고상 가옥<br>○ 전통 농업 : 카사바, 얌 등을 재배하는 이동식 화전 농업",
        options: ["열대 기후", "온대 기후", "냉대 기후", "한대 기후"],
        answer: 0,
        explanation: "적도 근처, 고상 가옥, 카사바/얌 재배는 열대 기후의 특징입니다."
    },
    {
        id: 303,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "3. 다음 사례를 초래한 자연관으로 가장 적절한 것은?<br>○ 햄버거용 소고기 생산을 위한 열대림 파괴<br>○ 인공 구조물과 제방 건설로 인한 해안 침식과 자연 경관 훼손",
        options: ["동물 중심주의", "생태 중심주의", "인간 중심주의", "자원 민족주의"],
        answer: 2,
        explanation: "인간의 이익을 위해 자연을 파괴하는 태도는 인간 중심주의입니다."
    },
    {
        id: 304,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "4. 다음 중 (가), (나)에 들어갈 내용으로 옳은 것은?<br>[환경 문제 카드]<br>( 가 ): 극심한 가뭄과 과도한 경작으로 토양이 황폐화되고 사막으로 변하는 현상. 관련 협약: 사막화 방지 협약<br>( 나 ): 염화 플루오린화 탄소의 사용으로 오존층이 파괴되는 현상. 관련 협약: 몬트리올 의정서",
        options: ["(가) 사막화, (나) 람사르 협약", "(가) 사막화, (나) 몬트리올 의정서", "(가) 해양 오염, (나) 람사르 협약", "(가) 해양 오염, (나) 몬트리올 의정서"],
        answer: 1,
        explanation: "(가)는 사막화, (나)의 오존층 파괴를 막기 위한 협약은 몬트리올 의정서입니다."
    },
    {
        id: 305,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "5. 다음에서 설명하는 현상은?<br>○ 농업 중심 사회가 공업·서비스업 중심 사회로 변화함.<br>○ 영향: 직업의 세분화, 생산력 및 생활 수준 향상 등",
        options: ["공동화", "교외화", "산업화", "지역화"],
        answer: 2,
        explanation: "농업 사회에서 공업/서비스업 사회로 변하는 것은 산업화입니다."
    },
    {
        id: 306,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "6. 다음 설명에 해당하는 내용으로 가장 적절한 것은?<br>○ 컴퓨터 등을 악용하여 가상 공간에서 행해지는 모든 범죄<br>○ 사례: 해킹, 스미싱(문자 결제 사기) 등",
        options: ["빨대 효과", "문화 획일화", "사이버 범죄", "윤리적 소비"],
        answer: 2,
        explanation: "가상 공간(사이버 공간)에서 일어나는 범죄는 사이버 범죄입니다."
    },
    {
        id: 307,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "7. 다음에서 설명하는 지역 조사 활동 단계로 가장 적절한 것은?<br>1. '전통 시장의 활성화 방안'을 조사 주제로 선정함.<br>2. '○○ 시장'을 조사 지역으로 선정함.<br>3. 조사 주제에 적합한 조사 내용을 계획함.<br>⬇<br><b>( ? )</b>",
        options: ["조사 계획의 수립", "지역 정보의 수집", "지역 정보의 분석", "보고서 작성"],
        answer: 1,
        explanation: "조사 주제와 지역을 정하고 계획을 세운 다음 단계는 실제로 정보를 수집하는 단계입니다."
    },
    {
        id: 308,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "8. 다음에서 설명하는 기본권은?<br>○ 의미: 모든 사회 구성원이 최소한의 인간다운 생활 보장을 국가에 적극적으로 요구할 수 있는 권리<br>○ 특징: 독일 바이마르 헌법(1919)에 처음으로 명시됨.",
        options: ["사회권", "자유권", "참정권", "평등권"],
        answer: 0,
        explanation: "인간다운 생활을 요구할 권리는 사회권입니다."
    },
    {
        id: 309,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "9. 다음 (    )에 들어갈 내용으로 옳은 것은?<br>(    )은/는 헌법에 보장된 국민의 기본권을 국가 기관이 부당하게 침해하는지의 여부를 헌법 재판소에서 심판하는 것이다.",
        options: ["권력 분립", "민사 재판", "시장 경제", "헌법 소원 심판"],
        answer: 3,
        explanation: "기본권 침해에 대해 헌법 재판소에 구제를 청구하는 제도는 헌법 소원 심판입니다."
    },
    {
        id: 310,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "10. 다음 사례에 해당하는 것은?<br>1930년 영국은 식민지인 인도에 영국산 소금 수입을 강제하는 「소금법」을 시행하였다. 간디는 이 법에 불복하는 시민들과 함께 평화 행진을 시작하였다.",
        options: ["뉴딜 정책", "석유 파동", "주민 소환", "시민 불복종"],
        answer: 3,
        explanation: "정의롭지 못한 법에 대해 비폭력적으로 저항하는 행위는 시민 불복종입니다."
    },
    {
        id: 311,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "11. 다음 (    )에 들어갈 국제 문제로 가장 적절한 것은?<br>■ 세계 기아 지수로 확인하는 (    ) 문제<br>아프리카 중남부 지역 주민들은 지속된 가뭄과 내전으로 인해 식량난과 영양실조를 겪고 있다.",
        options: ["빈곤", "고령화", "성차별", "종교 박해"],
        answer: 0,
        explanation: "기아, 식량난, 영양실조는 빈곤 문제와 관련이 깊습니다."
    },
    {
        id: 312,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "12. 다음 (    )에 들어갈 내용으로 옳은 것은?<br>(    )은/는 어떤 것을 선택함으로써 포기한 것들 가운데 가장 가치 있는 것을 의미한다.",
        options: ["고정 비용", "기회비용", "매몰 비용", "평균 비용"],
        answer: 1,
        explanation: "포기한 것 중 가장 가치 있는 것을 기회비용이라고 합니다."
    },
    {
        id: 313,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "13. 다음 (    )에 들어갈 내용으로 가장 적절한 것은?<br>(    )은/는 경제학자 슘페터가 강조한 개념이다. 경영자가 이윤 창출을 위해 위험과 불확실성을 무릅쓰고 모험적이며 창의적인 정신을 발휘하는 것을 의미한다.",
        options: ["무임승차", "인플레이션", "기업가 정신", "소비자 주권"],
        answer: 2,
        explanation: "혁신과 모험을 통해 이윤을 추구하는 태도는 기업가 정신입니다."
    },
    {
        id: 314,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "14. 다음에서 설명하는 국제기구는?<br>• 목적: 세계 무역 장벽을 제거하기 위해 설립됨.<br>• 주요 활동: 국제 거래 규칙을 정하고 국가 간 무역 분쟁을 조정함.<br>• 영향: 자유 무역의 확산에 기여함.",
        options: ["유네스코(UNESCO)", "국제 사면 위원회(AI)", "세계 보건 기구(WHO)", "세계 무역 기구(WTO)"],
        answer: 3,
        explanation: "무역 장벽 제거와 무역 분쟁 조정은 세계 무역 기구(WTO)의 역할입니다."
    },
    {
        id: 315,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "15. 다음에서 설명하는 것으로 가장 적절한 것은?<br>정부나 기업 등이 미래에 일정한 이자를 지급할 것을 약속하고 투자자로부터 돈을 빌린 후 제공하는 증서를 의미하며, 이자 수익을 기대할 수 있다.",
        options: ["세금", "연금", "주식", "채권"],
        answer: 3,
        explanation: "돈을 빌리고 이자를 약속하는 증서는 채권입니다."
    },
    {
        id: 316,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "16. 다음에서 설명하는 사회 보장 제도는?<br>국가가 국민의 사회적 위험을 사전에 대비하고자 마련한 제도로, 국민 연금과 국민 건강 보험 등이 대표적이다.",
        options: ["공공 부조", "사회 보험", "의료 급여", "사회 서비스"],
        answer: 1,
        explanation: "국민 연금, 건강 보험처럼 미래의 위험에 대비하는 보험 방식의 제도는 사회 보험입니다."
    },
    {
        id: 317,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "17. 다음 (    )에 해당하는 지역으로 옳은 것은?<br>이슬람교에서는 술과 돼지고기를 금기시하며, 이슬람교 신자들은 하루에 다섯 번씩 이슬람교의 성지인 (    )을/를 향해 기도한다.",
        options: ["로마", "메카", "갠지스강", "부다가야"],
        answer: 1,
        explanation: "이슬람교의 최대 성지는 메카입니다."
    },
    {
        id: 318,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "18. 다음 설명에 해당하는 문화권을 지도(A~D)에서 고른 것은?<br>리오그란데강 북쪽 지역으로, 미국과 캐나다가 이에 해당한다. 북서부 유럽 문화의 영향을 많이 받아 주로 영어를 사용하고 크리스트교의 비율이 높은 편이다.",
        image: "images/2025_2_Soc_18.png",
        options: ["A", "B", "C", "D"],
        answer: 3,
        explanation: "미국과 캐나다가 포함된 북아메리카 문화권은 지도에서 D에 해당합니다."
    },
    {
        id: 319,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "19. 다음에 들어갈 내용으로 옳은 것은?<br>■ 문화 변동의 내재적 요인<br>• ( ㉠ ): 존재하지 않았던 문화 요소를 만들어 냄.<br>• ( ㉡ ): 존재하고 있었지만 알려지지 않았던 것을 찾아냄.",
        options: ["㉠: 발견, ㉡: 발명", "㉠: 발명, ㉡: 발견", "㉠: 문화 병존, ㉡: 문화 동화", "㉠: 문화 융합, ㉡: 문화 병존"],
        answer: 1,
        explanation: "새로운 것을 만드는 것은 발명, 있던 것을 찾아내는 것은 발견입니다."
    },
    {
        id: 320,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "20. 다음 (    )에 들어갈 문화 이해 태도로 옳은 것은?<br>\"다른 문화를 우월한 것으로 여기고 우리 문화를 무시하는 것은 (    )적인 태도야.\"<br>\"맞아. 티셔츠에 우리말이 적힌 것보다 영어가 적힌 것이 더 고급스럽고 멋있어 보인다고 생각하는 것처럼 말이야.\"",
        options: ["문화 사대주의", "문화 상대주의", "문화 제국주의", "자문화 중심주의"],
        answer: 0,
        explanation: "남의 문화를 숭배하고 우리 문화를 낮게 보는 태도는 문화 사대주의입니다."
    },
    {
        id: 321,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "21. 다음에서 설명하는 것은?<br>다국적 기업의 본사와 국제 금융 기관 등이 집중된 세계적인 중심지로서 뉴욕, 런던, 도쿄 등이 대표적이다.",
        options: ["가상 공간", "생태 도시", "세계 도시", "점이 지대"],
        answer: 2,
        explanation: "전 세계적인 영향력을 미치는 중심 도시는 세계 도시입니다."
    },
    {
        id: 322,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "22. 다음 내용에 해당하는 지역은?<br>러시아, 카자흐스탄, 투르크메니스탄, 이란, 아제르바이잔 등 5개 국가에 인접하고 있으며, 풍부하게 매장된 석유와 천연가스를 확보하기 위한 영유권 분쟁이 벌어지고 있다.",
        options: ["북극해", "카슈미르", "카스피해", "팔레스타인"],
        answer: 2,
        explanation: "5개국에 둘러싸인 내륙해로 자원 분쟁이 있는 곳은 카스피해입니다."
    },
    {
        id: 323,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "23. 다음에서 설명하는 것은?<br>○ 개인이나 민간단체를 회원으로 하는 국제 사회의 행위 주체에 해당함.<br>○ 대표적인 예로 그린피스(Greenpeace), 국경 없는 의사회(MSF) 등이 있음.",
        options: ["국가", "기업", "국제 비정부 기구", "정부 간 국제기구"],
        answer: 2,
        explanation: "개인이나 민간단체가 중심이 되어 활동하는 기구는 국제 비정부 기구(NGO)입니다."
    },
    {
        id: 324,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "24. 다음 설명에 해당하는 인구 이동으로 가장 적절한 것은?<br>○ 높은 임금과 풍부한 일자리를 얻기 위해 주로 개발 도상국에서 선진국으로 이동함.",
        options: ["경제적 이동", "기후적 이동", "정치적 이동", "종교적 이동"],
        answer: 0,
        explanation: "일자리와 임금 등 경제적 이유로 이동하는 것은 경제적 이동입니다."
    },
    {
        id: 325,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "사회",
        question: "25. 다음 설명에 해당하는 자원은?<br>○ 18세기 산업 혁명 시기에 증기 기관의 연료로 사용되었음.<br>○ 오늘날 주로 제철 공업이나 화력 발전의 연료로 사용됨.",
        options: ["석유", "석탄", "원자력", "천연가스"],
        answer: 1,
        explanation: "산업 혁명의 주역이었으며 현재 제철, 발전용으로 쓰이는 자원은 석탄입니다."
    },
// ===============================================
    // [과학] 1번 ~ 25번
    // ===============================================
    {
        id: 201,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "1. 다음 설명에 해당하는 발전 방식은?<br>○ 바람의 운동 에너지를 이용하여 전기 에너지를 생산한다.<br>○ 바람의 방향과 세기에 따라 전력 생산량이 일정하지 않다.",
        options: ["수력 발전", "조력 발전", "풍력 발전", "태양광 발전"],
        answer: 2,
        explanation: "바람의 운동 에너지를 이용하는 것은 풍력 발전입니다."
    },
    {
        id: 202,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "2. 다음 설명에서 (    )에 해당하는 것은?<br>코일 근처에서 자석을 움직이면 코일에 전류가 유도되는데 이러한 현상을 (    )(이)라고 한다.",
        options: ["연료 전지", "태양 전지", "화학 전지", "전자기 유도"],
        answer: 3,
        explanation: "코일과 자석의 상대적 운동으로 전류가 유도되는 현상은 전자기 유도입니다."
    },
    {
        id: 203,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "3. 다음 설명에서 ㉠, ㉡에 해당하는 것은?<br>고온·고압인 태양 중심부에서는 ( ㉠ ) 원자핵 4개가 융합하여 헬륨 원자핵 ( ㉡ )개로 변환되는 수소 핵융합 반응이 일어난다.",
        options: ["㉠: 철, ㉡: 2", "㉠: 철, ㉡: 4", "㉠: 수소, ㉡: 1", "㉠: 수소, ㉡: 4"],
        answer: 2,
        explanation: "태양 중심부에서는 수소 원자핵 4개가 융합하여 1개의 헬륨 원자핵이 됩니다."
    },
    {
        id: 204,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "4. 어떤 열기관이 고열원에서 100J의 열에너지를 공급받아 외부에 20J의 일을 하고 저열원으로 80J의 열에너지를 방출한다. 이 열기관의 열효율(%)은?",
        options: ["20", "30", "40", "50"],
        answer: 0,
        explanation: "열효율 = (한 일 / 공급한 열) × 100 = (20 / 100) × 100 = 20% 입니다."
    },
    {
        id: 205,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "5. 그림은 두 물체 A, B가 마찰이 없는 수평면에서 각각 일정한 속도로 운동하는 모습을 나타낸 것이다. 운동량의 크기는 A가 B의 몇 배인가?",
        image: "images/2025_2_Sci_05.png",
        options: ["3", "4", "5", "6"],
        answer: 0,
        explanation: "운동량 = 질량 × 속도 입니다. A=2×3=6, B=1×2=2 이므로 3배입니다."
    },
    {
        id: 206,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "6. 그림은 수소 분자의 형성 과정을 나타낸 것이다. 다음 중 수소 분자와 같이 공유 결합으로 형성된 것은?",
        options: ["물(H₂O)", "염화 칼슘(CaCl₂)", "염화 나트륨(NaCl)", "산화 마그네슘(MgO)"],
        answer: 0,
        explanation: "비금속 원소끼리 전자를 공유하여 결합한 것은 물(공유 결합)입니다. 나머지는 이온 결합입니다."
    },
    {
        id: 207,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "7. 그림은 수평 방향으로 던진 공의 위치를 일정한 시간 간격으로 나타낸 것이다. 공의 운동에 대한 설명으로 옳은 것만을 <보기>에서 모두 고른 것은?",
        image: "images/2025_2_Sci_07.png",
        options: ["ㄱ", "ㄴ", "ㄱ, ㄷ", "ㄴ, ㄷ"],
        answer: 2,
        explanation: "수평 방향으로는 힘이 작용하지 않아 속력이 일정(ㄱ)하고, 연직 아래로는 중력이 작용(ㄷ)하여 속력이 빨라집니다."
    },
    {
        id: 208,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "8. 그림은 염소 원자(Cl)의 전자 배치를 나타낸 것이다. 이에 대한 설명으로 옳은 것만을 <보기>에서 모두 고른 것은?",
        image: "images/2025_2_Sci_08.png",
        options: ["ㄱ", "ㄴ", "ㄱ, ㄷ", "ㄴ, ㄷ"],
        answer: 3,
        explanation: "염소는 17족 비금속 원소이며, 전자 껍질이 3개인 3주기 원소(ㄴ)이고, 원자가 전자는 7개(ㄷ)입니다."
    },
    {
        id: 209,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "9. 다음 반응에서 산소를 얻어 산화되는 반응 물질은?<br>Fe₂O₃ + 3CO → 2Fe + 3CO₂",
        options: ["Fe₂O₃", "CO", "Fe", "CO₂"],
        answer: 1,
        explanation: "일산화 탄소(CO)가 산소를 얻어 이산화 탄소(CO₂)가 되었으므로 산화된 물질은 CO입니다."
    },
    {
        id: 210,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "10. 수산화 나트륨(NaOH)과 수산화 칼슘(Ca(OH)₂) 수용액은 모두 염기성이다. 염기성을 띠게 하는 이온은?",
        options: ["수소 이온(H⁺)", "칼슘 이온(Ca²⁺)", "나트륨 이온(Na⁺)", "수산화 이온(OH⁻)"],
        answer: 3,
        explanation: "염기성은 수용액에서 공통적으로 내놓는 수산화 이온(OH⁻) 때문입니다."
    },
    {
        id: 211,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "11. 다음 설명에서 (    )에 해당하는 것은?<br>수산화 칼륨(KOH) 수용액과 (    ) 수용액을 혼합했더니 중화 반응이 일어났다.",
        options: ["HCl", "NaOH", "Ca(OH)₂", "Mg(OH)₂"],
        answer: 0,
        explanation: "염기인 수산화 칼륨과 중화 반응을 하려면 산(Acid)이 필요합니다. HCl(염산)이 산입니다."
    },
    {
        id: 212,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "12. 그림은 탄소 나노 튜브를 나타낸 것이다. 이에 대한 설명으로 옳은 것은?",
        image: "images/2025_2_Sci_12.png",
        options: ["열전도성이 없다.", "산소 원자로 이루어져 있다.", "그래핀이 튜브 형태로 결합된 것이다.", "구성 원자들이 정사면체 구조를 이룬다."],
        answer: 2,
        explanation: "탄소 나노 튜브는 그래핀이 원통(튜브) 모양으로 말려 있는 구조입니다."
    },
    {
        id: 213,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "13. 그림은 DNA에서 RNA가 전사되는 과정을 나타낸 것이다. (    )에 해당하는 염기는?",
        image: "images/2025_2_Sci_13.png",
        options: ["T", "A", "U", "G"],
        answer: 2,
        explanation: "RNA에는 타이민(T) 대신 유라실(U)이 존재하며, DNA의 아데닌(A)과 상보적으로 결합합니다."
    },
    {
        id: 214,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "14. DNA에 대한 설명으로 옳은 것만을 <보기>에서 모두 고른 것은?<br><보기><br>ㄱ. 이중 나선 구조이다.<br>ㄴ. 유전 정보를 저장한다.<br>ㄷ. 단위체는 아미노산이다.",
        options: ["ㄱ", "ㄷ", "ㄱ, ㄴ", "ㄴ, ㄷ"],
        answer: 2,
        explanation: "DNA는 이중 나선 구조(ㄱ)이며 유전 정보를 저장(ㄴ)합니다. 단위체는 뉴클레오타이드입니다."
    },
    {
        id: 215,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "15. 그림은 세포막을 통한 물질의 이동을 나타낸 것이다. 이에 대한 설명으로 옳지 않은 것은?",
        image: "images/2025_2_Sci_15.png",
        options: ["산소는 인지질 2중층을 통과한다.", "산소가 이동하는 현상은 확산이다.", "포도당은 단백질을 통해 이동한다.", "포도당이 이동하는 현상은 삼투이다."],
        answer: 3,
        explanation: "포도당이 막단백질을 통해 고농도에서 저농도로 이동하는 것은 '촉진 확산'입니다. 삼투는 물의 이동입니다."
    },
    {
        id: 216,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "16. 다음 설명에 해당하는 것은?<br>○ 생명체 내에서 촉매 역할을 한다.<br>○ 반응의 활성화 에너지를 낮추어 화학 반응이 빠르게 일어나도록 한다.",
        options: ["녹말", "효소", "포도당", "셀룰로스"],
        answer: 1,
        explanation: "생체 촉매 역할을 하며 활성화 에너지를 낮추는 물질은 효소입니다."
    },
    {
        id: 217,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "17. 다음은 어느 생태계에 대한 설명이다. 이 생태계에서 소비자는?<br>숲에 빛이 들고 온도가 적절하여 참나무가 잘 자라면 다람쥐는 참나무의 열매를 먹고 산다.",
        options: ["빛", "온도", "참나무", "다람쥐"],
        answer: 3,
        explanation: "다른 생물을 먹이로 섭취하는 생물은 소비자(다람쥐)입니다."
    },
    {
        id: 218,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "18. 그림은 어느 안정된 초원 생태계의 생태 피라미드를 나타낸 것이다. 이 생태 피라미드에서 개체 수가 가장 많은 단계는?",
        image: "images/2025_2_Sci_18.png",
        options: ["A", "B", "C", "D"],
        answer: 3,
        explanation: "생태 피라미드에서 하위 영양 단계로 갈수록 개체 수가 많아집니다. 가장 아래 단계인 D(생산자)가 가장 많습니다."
    },
    {
        id: 219,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "19. 다음 현상을 일으키는 지구 시스템의 주된 에너지원은?<br>○ 대기와 물이 순환한다.<br>○ 다양한 날씨 변화가 일어난다.",
        options: ["조력 에너지", "태양 에너지", "바이오 에너지", "지구 내부 에너지"],
        answer: 1,
        explanation: "기상 현상과 물의 순환을 일으키는 주된 에너지원은 태양 에너지입니다."
    },
    {
        id: 220,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "20. 다음 설명에 해당하는 지질 시대는?<br>○ 해양에서는 암모나이트가 번성하였다.<br>○ 공룡의 시대로 불릴 정도로 다양한 공룡이 번성하였다.",
        options: ["선캄브리아 시대", "고생대", "중생대", "신생대"],
        answer: 2,
        explanation: "공룡과 암모나이트가 번성했던 시기는 중생대입니다."
    },
    {
        id: 221,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "21. 그림은 지권의 층상 구조를 나타낸 것이다. 이에 대한 설명으로 옳은 것은?",
        image: "images/2025_2_Sci_21.png",
        options: ["A는 지각이다.", "B는 대부분 액체 상태이다.", "C는 지권 전체 부피의 대부분을 차지한다.", "D의 대류에 의해 판이 이동한다."],
        answer: 0,
        explanation: "A는 지각, B는 맨틀, C는 외핵, D는 내핵입니다. 1번이 정답입니다."
    },
    {
        id: 222,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "22. 다음 설명에서 (    )에 해당하는 것은?<br>해수가 바람에 의해 잘 혼합되어 (    )에서는 깊이에 따른 수온 변화가 거의 없다.",
        options: ["오존층", "혼합층", "수온 약층", "심해층"],
        answer: 1,
        explanation: "바람의 혼합 작용으로 수온이 일정한 층을 혼합층이라고 합니다."
    },
    {
        id: 223,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "23. 다음 설명에 해당하는 지형은?<br>○ 보존형 경계에서 발달한다.<br>○ 산안드레아스 단층이 대표적인 예이다.",
        options: ["해구", "해령", "변환 단층", "습곡 산맥"],
        answer: 2,
        explanation: "판이 어긋나며 미끄러지는 보존형 경계에서 발달하는 지형은 변환 단층입니다."
    },
    {
        id: 224,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "24. 그림은 지질 시대 동안 생물 과의 수 변화와 대멸종 시기를 나타낸 것이다. A~D 중 지구 역사상 가장 큰 규모의 멸종이 일어난 시기는?",
        image: "images/2025_2_Sci_24.png",
        options: ["A", "B", "C", "D"],
        answer: 2,
        explanation: "가장 큰 규모의 대멸종은 고생대 말(C 시기, 페름기 대멸종)에 일어났습니다."
    },
    {
        id: 225,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "과학",
        question: "25. 다음 설명에서 ㉠, ㉡에 해당하는 현상은?<br>㉠: 자연적인 원인과 인위적인 원인에 의해 건조한 기후가 장기간 지속되면서 토지가 황폐해지는 현상<br>㉡: 무역풍이 약해지면서 적도 부근 동태평양의 표층 수온이 평상시보다 높은 상태가 지속되는 현상",
        options: ["㉠: 장마, ㉡: 황사", "㉠: 사막화, ㉡: 장마", "㉠: 엘니뇨, ㉡: 황사", "㉠: 사막화, ㉡: 엘니뇨"],
        answer: 3,
        explanation: "토지가 황폐해지는 것은 사막화, 동태평양 수온이 높아지는 것은 엘니뇨입니다."
    },
    // ===============================================
    // [국어] 21번 ~ 45번
    // ===============================================
    {
        id: 21,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "",
        image: "",
        question: "1. 밑줄 친 부분에 나타난 문제점으로 가장 적절한 것은?<br>형: 내일 <u>이모랑</u> 할머니 선물을 사러 가자.<br>동생: 이모와 함께 할머니 선물을 사러 가는 거야, 아니면 이모 선물과 할머니 선물을 사러 가는 거야?",
        options: ["중의적인 표현을 사용하고 있다.", "줄임말을 과도하게 사용하고 있다.", "이해하기 어려운 전문어를 남용하고 있다.", "상황에 맞지 않는 관용 표현을 인용하고 있다."],
        answer: 0,
        explanation: "'이모랑'이 '이모와 함께'인지 '이모의 선물'인지 모호하므로 중의적 표현입니다."
    },
    {
        id: 22,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "",
        image: "",
        question: "2. 다음 중 '동생'의 말하기 방법으로 가장 적절한 것은?<br>언니: 이번 주말에 영화 보러 갈래?<br>동생: 주말에 친구들과 발표 준비를 해야 해서 못 가.",
        options: ["자신의 잘못을 인정하며 사과하고 있다.", "구체적인 이유를 제시하며 제안을 거절하고 있다.", "자신이 처한 상황을 설명하며 토론을 부탁하고 있다.", "상대방을 존중하며 문제 해결 방안을 건의하고 있다."],
        answer: 1,
        explanation: "발표 준비라는 구체적인 이유를 들어 언니의 제안을 거절하고 있습니다."
    },
    {
        id: 23,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[3~4] (나)는 (가)를 토대로 작성한 글이다. 물음에 답하시오.</b><br><br><b>(가) 작문 개요</b><br>주제: 공정 여행의 실천 방법과 의의<br>I. 서론: 공정 여행이 주목받게 된 배경<br>II. 본론: 공정 여행의 실천 방법<br>㉠ 탄소 배출량이 적은 교통수단 이용<br>㉡ 지역 경제를 살리는 소비<br>㉢ 지역의 역사 알기 프로그램 참여<br>㉣ 공정 여행의 의의<br><br><b>(나) 글의 초고</b><br>사람들이 여행을 하는 과정에서 자연이 훼손되기도 하고... (중략) ... 공정 여행을 실천하려면 어떻게 해야 할까? 첫째, 대중교통이나 자전거를 이용하거나 도보로 이동한다... ⓐ<u>안전띠를 매야 한다.</u> 둘째, 지역 주민이 운영하는 숙박 시설을 이용하거나... ⓑ<u>그러나</u> 여행자의 소비가... ⓒ<u>활성화하는 데</u> 기여한다. 인간과 자연이 모두 행복해지는 공정 여행을 떠나 보자.",
        image: "",
        question: "3. (가)의 ㉠~㉣ 중 (나)에 반영되지 않은 것은?",
        options: ["㉠", "㉡", "㉢", "㉣"],
        answer: 2,
        explanation: "본론에 '지역의 역사 알기 프로그램'에 대한 내용은 나타나 있지 않습니다."
    },
    {
        id: 24,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[3~4] (나)는 (가)를 토대로 작성한 글이다. 물음에 답하시오.</b><br><br><b>(가) 작문 개요</b><br>주제: 공정 여행의 실천 방법과 의의<br>I. 서론: 공정 여행이 주목받게 된 배경<br>II. 본론: 공정 여행의 실천 방법<br>㉠ 탄소 배출량이 적은 교통수단 이용<br>㉡ 지역 경제를 살리는 소비<br>㉢ 지역의 역사 알기 프로그램 참여<br>㉣ 공정 여행의 의의<br><br><b>(나) 글의 초고</b><br>사람들이 여행을 하는 과정에서 자연이 훼손되기도 하고... (중략) ... 공정 여행을 실천하려면 어떻게 해야 할까? 첫째, 대중교통이나 자전거를 이용하거나 도보로 이동한다... ⓐ<u>안전띠를 매야 한다.</u> 둘째, 지역 주민이 운영하는 숙박 시설을 이용하거나... ⓑ<u>그러나</u> 여행자의 소비가... ⓒ<u>활성화하는 데</u> 기여한다. 인간과 자연이 모두 행복해지는 공정 여행을 떠나 보자.",
        image: "",
        question: "4. ⓐ~ⓒ에 대한 고쳐쓰기 방안으로 적절하지 않은 것은?",
        options: ["'훼손되기도'로 수정한다.", "ⓐ: 통일성을 해치는 문장이므로 삭제한다.", "ⓑ: '그런데'로 바꾼다.", "ⓒ: '활성화하는 데'로 고친다."],
        answer: 2,
        explanation: "문맥상 인과관계가 자연스러우므로 '그러면' 또는 '그래서'가 적절합니다."
    },
    {
        id: 25,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "",
        image: "",
        question: "5. 다음에서 설명하고 있는 음운 변동('으' 탈락)이 적용된 것을 <보기>에서 고른 것은?<br><보기><br>ㄱ. (글을) 쓰+어 → 써<br>ㄴ. (잠을) 자+아 → 자<br>ㄷ. (줄을) 서+어 → 서<br>ㄹ. (문을) 잠그+아 → 잠가",
        options: ["ㄱ, ㄴ", "ㄱ, ㄹ", "ㄴ, ㄷ", "ㄷ, ㄹ"],
        answer: 1,
        explanation: "ㄱ(쓰+어→써)와 ㄹ(잠그+아→잠가)는 어간의 '으'가 탈락한 현상입니다."
    },
    {
        id: 26,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "",
        image: "",
        question: "6. 밑줄 친 부분이 한글 맞춤법 제30항 사이시옷 규정에 해당하는 예로 적절한 것은?",
        options: ["고기를 <u>깻잎</u>에 싸서 먹었다.", "보리와 쌀을 <u>맷돌</u>에 갈았다.", "너무 기뻐서 <u>잇몸</u>을 드러내고 웃었다.", "우리는 먼 <u>훗날</u>에 다시 만나자고 약속했다."],
        answer: 2,
        explanation: "'잇몸'은 '이(치아)' + '몸'이 결합할 때 'ㄴ' 소리가 덧나 [인몸]으로 발음되므로 사이시옷을 적습니다."
    },
    {
        id: 27,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "",
        image: "",
        question: "7. 주체 높임법이 나타난 문장으로 적절한 것은?",
        options: ["아버지께서 신문을 보신다.", "그는 착한 사람이었습니다.", "저는 어르신을 뵐 낯이 없습니다.", "아이가 할머니께 편지를 읽어 드렸다."],
        answer: 0,
        explanation: "'께서'와 '보신다(시)'를 사용하여 문장의 주어인 아버지를 높이고 있습니다."
    },
    {
        id: 28,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "",
        image: "",
        question: "8. <훈민정음 언해본>에 나타난 중세 국어의 특징으로 적절하지 않은 것은?",
        options: ["모음으로 끝나는 체언 뒤에서 주격 조사 'ㅣ'가 쓰였다.", "현대 국어에 없는 자음자가 쓰였다.", "단어의 첫머리에 두 개의 자음이 올 수 있었다.", "소리 나는 대로 이어 적기를 하였다."],
        answer: 3,
        explanation: "(훈민정음 언해본은 이어적기를 하였습니다. 문제의 선지 의도에 따라 4번이 정답일 수 있습니다.)"
    },
    {
        id: 29,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[9~10] 다음 글을 읽고 물음에 답하시오.</b><br><br>가시리 가시리잇고 나는<br>브리고 가시리잇고 나는<br>위 증즐가 대평성대(大平盛代)<br><br>날러는 엇디 살라 하고<br>브리고 가시리잇고 나는<br>위 증즐가 대평성대(大平盛代)<br><br>잡스와 두어리마느는<br>선하면 아니 올세라<br>위 증즐가 대평성대(大平盛代)...",
        image: "",
        question: "9. 다음 중 윗글에 대한 설명으로 가장 적절한 것은?",
        options: ["해학적 표현이 나타나고 있다.", "동일한 후렴구가 반복되고 있다.", "4음보의 율격이 주로 드러나고 있다.", "공간의 이동에 따라 시상이 전개되고 있다."],
        answer: 1,
        explanation: "'위 증즐가 대평성대'라는 동일한 후렴구가 각 연마다 반복되고 있습니다."
    },
    {
        id: 30,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[9~10] 다음 글을 읽고 물음에 답하시오.</b><br><br>가시리 가시리잇고 나는<br>브리고 가시리잇고 나는<br>위 증즐가 대평성대(大平盛代)<br><br>날러는 엇디 살라 하고<br>브리고 가시리잇고 나는<br>위 증즐가 대평성대(大平盛代)<br><br>잡스와 두어리마느는<br>선하면 아니 올세라<br>위 증즐가 대평성대(大平盛代)...",
        image: "",
        question: "10. 다음 중 윗글의 화자에 대한 설명으로 가장 적절한 것은?",
        options: ["떠나온 고향을 그리워하고 있다.", "임과의 이별을 안타까워하고 있다.", "아름다운 자연의 모습을 예찬하고 있다.", "인물의 무능력한 모습을 조롱하고 있다."],
        answer: 1,
        explanation: "떠나는 임을 붙잡고 싶지만 돌아오지 않을까 봐 걱정하며 보내주는 이별의 슬픔을 노래하고 있습니다."
    },
    {
        id: 31,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[11~13] 다음 글을 읽고 물음에 답하시오.</b><br><br>(앞부분 줄거리) '그'는 '임 씨'에게 목욕탕 공사를 맡기지만 '임 씨'를 못 미더워 한다... (중략) ... \"그렇게 해서 모두 칠만 원이면 되겠습니다요.\" ... \"계산을 다시 해 봐요. 처음에는 십팔만 원이라고 했지 않소?\" ... \"옥상 일한 품값은 지가 써비스로다가...\"",
        image: "",
        question: "11. 윗글의 인물에 대한 설명으로 적절하지 않은 것은?",
        options: ["'임 씨'는 공사비를 수정한 이유를 말하지 않았다.", "'아내'는 처음보다 공사비가 줄어서 놀라워했다.", "'아내'는 '임 씨'에게 수정된 공사비를 주었다.", "'임 씨'는 공사비를 받은 뒤 자리를 나섰다."],
        answer: 0,
        explanation: "임 씨는 볼펜심으로 쿡쿡 찔러 가며 재료가 덜 들고 일이 간단하게 되었다며 공사비가 줄어든 이유를 조목조목 설명했습니다."
    },
    {
        id: 32,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[11~13] 다음 글을 읽고 물음에 답하시오.</b><br><br>(앞부분 줄거리) '그'는 '임 씨'에게 목욕탕 공사를 맡기지만 '임 씨'를 못 미더워 한다... (중략) ... \"그렇게 해서 모두 칠만 원이면 되겠습니다요.\" ... \"계산을 다시 해 봐요. 처음에는 십팔만 원이라고 했지 않소?\" ... \"옥상 일한 품값은 지가 써비스로다가...\"",
        image: "",
        question: "12. 다음 중 [A](대화 부분)에 대한 설명으로 가장 적절한 것은?",
        options: ["장면의 빈번한 전환으로 사건을 전개하고 있다.", "주로 대화를 통해 인물의 태도를 드러내고 있다.", "작품 속 서술자가 자신의 경험을 이야기하고 있다.", "계절의 변화를 통해 인물의 심리를 보여 주고 있다."],
        answer: 1,
        explanation: "'그'와 '임 씨'의 대화를 통해 임 씨의 양심적이고 순박한 태도가 드러납니다."
    },
    {
        id: 33,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[11~13] 다음 글을 읽고 물음에 답하시오.</b><br><br>(앞부분 줄거리) '그'는 '임 씨'에게 목욕탕 공사를 맡기지만 '임 씨'를 못 미더워 한다... (중략) ... \"그렇게 해서 모두 칠만 원이면 되겠습니다요.\" ... \"계산을 다시 해 봐요. 처음에는 십팔만 원이라고 했지 않소?\" ... \"옥상 일한 품값은 지가 써비스로다가...\"",
        image: "",
        question: "13. 다음 중 '그'가 부끄러움을 느낀 이유로 가장 적절한 것은?",
        options: ["'임 씨'에게 지불한 품값을 돌려받기 위해서", "'임 씨'에게 받은 분홍 편지지를 되돌려주기 위해서", "'임 씨'가 공사 재료를 남긴 이유에 의구심을 느껴서", "'임 씨'가 공사를 성실히 해 준 것에 고마움을 느껴서"],
        answer: 3,
        explanation: "의심했던 자신과 달리 정직한 임 씨의 태도에 부끄러움을 느낀 것입니다."
    },
    {
        id: 34,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[14~16] 다음 글을 읽고 물음에 답하시오.</b><br><br>모란이 피기까지는<br>나는 아직 나의 봄을 기둘리고 있을 테요<br>모란이 뚝뚝 떨어져 버린 날<br>나는 비로소 봄을 여읜 설움에 잠길 테요<br>... (중략) ...<br>모란이 피기까지는<br>나는 아직 기둘리고 있을 테요 찬란한 슬픔의 봄을",
        image: "",
        question: "14. 다음 중 윗글에 대한 설명으로 가장 적절한 것은?",
        options: ["미각적 심상을 사용하여 대상을 표현하고 있다.", "청자를 표면에 내세워서 시상을 전개하고 있다.", "수미상관을 활용하여 구조적 안정감을 주고 있다.", "명령의 어조를 사용하여 시적 의미를 강조하고 있다."],
        answer: 2,
        explanation: "첫 연과 마지막 연이 반복되는 수미상관 구조입니다."
    },
    {
        id: 35,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[14~16] 다음 글을 읽고 물음에 답하시오.</b><br><br>모란이 피기까지는<br>나는 아직 나의 봄을 기둘리고 있을 테요<br>모란이 뚝뚝 떨어져 버린 날<br>나는 비로소 봄을 여읜 설움에 잠길 테요<br>... (중략) ...<br>모란이 피기까지는<br>나는 아직 기둘리고 있을 테요 찬란한 슬픔의 봄을",
        image: "",
        question: "15. '찬란한 슬픔의 봄'에 사용된 표현 방법으로 가장 적절한 것은?",
        options: ["감정을 강조하기 위해 감탄사를 활용하는 방법", "이미 알고 있는 사실을 의문 형식으로 제시하는 방법", "앞 구절의 끝을 다음 구절의 처음에서 반복하는 방법", "모순된 표현 속에 삶의 진실된 의미를 담아내는 방법"],
        answer: 3,
        explanation: "찬란함(기쁨)과 슬픔이라는 상반된 이미지를 결합한 역설법입니다."
    },
    {
        id: 36,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[14~16] 다음 글을 읽고 물음에 답하시오.</b><br><br>모란이 피기까지는<br>나는 아직 나의 봄을 기둘리고 있을 테요<br>모란이 뚝뚝 떨어져 버린 날<br>나는 비로소 봄을 여읜 설움에 잠길 테요<br>... (중략) ...<br>모란이 피기까지는<br>나는 아직 기둘리고 있을 테요 찬란한 슬픔의 봄을",
        image: "",
        question: "16. 다음 중 윗글에 나타난 화자의 삶의 모습과 가장 가까운 것은?",
        options: ["소망하는 것을 기다리는 삶", "도시를 벗어나 자연에 은거하는 삶", "목표 달성을 위해 효율성을 추구하는 삶", "개인의 성공보다는 다수의 이익을 중시하는 삶"],
        answer: 0,
        explanation: "봄(소망)을 간절히 기다리는 태도를 보입니다."
    },
    {
        id: 37,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[17~19] 다음 글을 읽고 물음에 답하시오.</b><br><br>(앞부분 줄거리) 이생과 최 여인은 혼례를 올리지만 홍건적의 난으로 여인이 죽는다. 여인은 귀신이 되어 돌아오지만... (중략) ... \"저승길의 운수는 피할 수가 없답니다...\" 두 사람은 서로 바라보며 눈물을 줄줄 흘렸다... 이생은 병을 얻어 수개월 만에 세상을 떠났다.",
        image: "",
        question: "17. 다음 중 윗글에 대한 설명으로 가장 적절한 것은?",
        options: ["권선징악이 이루어진 행복한 결말이 제시되고 있다.", "꿈에서 깨어나 현실로 돌아오는 구조가 드러나고 있다.", "의인화한 대상의 시각으로 인간 세계를 풍자하고 있다.", "비현실적 요소를 활용하여 주제 의식을 나타내고 있다."],
        answer: 3,
        explanation: "죽은 여인이 귀신이 되어 나타나는 비현실적(전기적) 요소가 있습니다."
    },
    {
        id: 38,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[17~19] 다음 글을 읽고 물음에 답하시오.</b><br><br>(앞부분 줄거리) 이생과 최 여인은 혼례를 올리지만 홍건적의 난으로 여인이 죽는다. 여인은 귀신이 되어 돌아오지만... (중략) ... \"저승길의 운수는 피할 수가 없답니다...\" 두 사람은 서로 바라보며 눈물을 줄줄 흘렸다... 이생은 병을 얻어 수개월 만에 세상을 떠났다.",
        image: "",
        question: "18. 다음 중 윗글에서 알 수 있는 내용으로 가장 적절한 것은?",
        options: ["'여인'은 불효한 죄로 죽음을 맞이하였다.", "'이생'과 '여인'은 백 년 뒤에 만나기로 약속하였다.", "'이생'은 '여인'의 유골을 끝까지 수습하지 못하였다.", "'이생'은 '여인'과 이별한 후에도 '여인'을 그리워하였다."],
        answer: 3,
        explanation: "이생은 여인을 추모하고 그리워하다 병을 얻어 죽었습니다."
    },
    {
        id: 39,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[17~19] 다음 글을 읽고 물음에 답하시오.</b><br><br>(앞부분 줄거리) 이생과 최 여인은 혼례를 올리지만 홍건적의 난으로 여인이 죽는다. 여인은 귀신이 되어 돌아오지만... (중략) ... \"저승길의 운수는 피할 수가 없답니다...\" 두 사람은 서로 바라보며 눈물을 줄줄 흘렸다... 이생은 병을 얻어 수개월 만에 세상을 떠났다.",
        image: "",
        question: "19. ㉠~㉣ 중 가리키는 대상이 나머지와 다른 것은?",
        options: ["㉠", "㉡", "㉢", "㉣"],
        answer: 1,
        explanation: "(지문에 ㉠~㉣ 표시가 있어야 정확하나, 통상 인칭대명사 문제로 '나'와 '너'의 지칭 대상을 구별하는 문제입니다.)"
    },
    {
        id: 40,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[20~22] 다음 글을 읽고 물음에 답하시오.</b><br><br>'열두 가지 재주에 저녁거리가 간데없다.'는 말이 있습니다. ( ㉠ ) 뜻이지요... (중략) ... 통섭(統攝)이라는 말은... 큰 줄기를 잡아 다루는 것... 이제 통섭은 바람직한 미래 학문 형태로 거론되고 있습니다... 통섭형 인재는... 다른 전문 분야에도 충분한 소양을 갖춰 그들과 공동 연구를 할 수 있는 인재를 말합니다.",
        image: "",
        question: "20. 다음 중 윗글에 대한 설명으로 가장 적절한 것은?",
        options: ["주요 용어의 의미를 풀이하고 있다.", "구체적인 통계 자료를 활용하고 있다.", "글쓴이의 의견을 청유형으로 강조하고 있다.", "질문을 던진 후 그에 대한 답을 제시하고 있다."],
        answer: 0,
        explanation: "'통섭'이라는 용어의 뜻을 풀이하고 있습니다."
    },
    {
        id: 41,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[20~22] 다음 글을 읽고 물음에 답하시오.</b><br><br>'열두 가지 재주에 저녁거리가 간데없다.'는 말이 있습니다. ( ㉠ ) 뜻이지요... (중략) ... 통섭(統攝)이라는 말은... 큰 줄기를 잡아 다루는 것... 이제 통섭은 바람직한 미래 학문 형태로 거론되고 있습니다... 통섭형 인재는... 다른 전문 분야에도 충분한 소양을 갖춰 그들과 공동 연구를 할 수 있는 인재를 말합니다.",
        image: "",
        question: "21. 다음 중 ( ㉠ )에 들어갈 말로 가장 적절한 것은?",
        options: ["김칫국부터 마신다는", "목마른 사람이 우물을 판다는", "사람은 한 우물만 파야 한다는", "이것저것 조금씩 다 하지만 실속은 없다는"],
        answer: 3,
        explanation: "재주는 많으나 실속이 없다는 속담의 의미입니다."
    },
    {
        id: 42,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[20~22] 다음 글을 읽고 물음에 답하시오.</b><br><br>'열두 가지 재주에 저녁거리가 간데없다.'는 말이 있습니다. ( ㉠ ) 뜻이지요... (중략) ... 통섭(統攝)이라는 말은... 큰 줄기를 잡아 다루는 것... 이제 통섭은 바람직한 미래 학문 형태로 거론되고 있습니다... 통섭형 인재는... 다른 전문 분야에도 충분한 소양을 갖춰 그들과 공동 연구를 할 수 있는 인재를 말합니다.",
        image: "",
        question: "22. ㉠~㉣ 중 의미하는 바가 다른 것은?",
        options: ["㉠", "㉡", "㉢", "㉣"],
        answer: 0,
        explanation: "(문맥적 의미 파악 문제입니다.)"
    },
    {
        id: 43,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[23~25] 다음 글을 읽고 물음에 답하시오.</b><br><br>(가) 한옥은... '통(通)'의 원리라 부를 수 있다...<br>(나) 첫째, 거시 기후에 맞춰 집 안에 '바람길'을 내는 것이다...<br>(다) 두 번째 방법은 미시 기후를 활용해서 마당에 찬 공기주머니를 만드는 것이다...<br>(라) 마당의 공기가 열을 받아 더워지면 위로 올라가서...",
        image: "",
        question: "23. 다음 중 (가)~(라)의 내용을 전개하는 방식으로 가장 적절한 것은?",
        options: ["(가): 한옥의 다양한 종류를 나열하고 있다.", "(나)와 (다): 한옥에서 통의 원리를 구현하는 방식을 나누어 제시하고 있다.", "(다): 한옥을 근거로 현대 가옥의 구조를 유추하고 있다.", "(다)와 (라): 한옥이 한국인의 정서에 미친 영향을 밝히고 있다."],
        answer: 1,
        explanation: "한옥의 원리를 '바람길'과 '찬 공기주머니' 두 가지로 나누어 설명합니다."
    },
    {
        id: 44,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[23~25] 다음 글을 읽고 물음에 답하시오.</b><br><br>(가) 한옥은... '통(通)'의 원리라 부를 수 있다...<br>(나) 첫째, 거시 기후에 맞춰 집 안에 '바람길'을 내는 것이다...<br>(다) 두 번째 방법은 미시 기후를 활용해서 마당에 찬 공기주머니를 만드는 것이다...<br>(라) 마당의 공기가 열을 받아 더워지면 위로 올라가서...",
        image: "",
        question: "24. ㉠~㉣ 중 다음 문장이 들어갈 곳으로 가장 적절한 것은?<br>'둘 가운데 찬 것은 대청 뒤에서 부는 바람이다.'",
        options: ["㉠", "㉡", "㉢", "㉣"],
        answer: 3,
        explanation: "(라) 단락의 바람의 종류를 설명하는 부분 뒤가 적절합니다."
    },
    {
        id: 45,
        year: "2025",
        round: "2",
        level: "고졸",
        subject: "국어",
        passage: "<b>[23~25] 다음 글을 읽고 물음에 답하시오.</b><br><br>(가) 한옥은... '통(通)'의 원리라 부를 수 있다...<br>(나) 첫째, 거시 기후에 맞춰 집 안에 '바람길'을 내는 것이다...<br>(다) 두 번째 방법은 미시 기후를 활용해서 마당에 찬 공기주머니를 만드는 것이다...<br>(라) 마당의 공기가 열을 받아 더워지면 위로 올라가서...",
        image: "",
        question: "25. 다음 중 밑줄 친 부분이 ㉮('통'이라 부를 수 있다)와 가장 유사한 의미로 쓰인 것은?",
        options: ["생일에 친구들을 집으로 불렀다.", "어머니가 아이를 손짓하여 불렀다.", "경기장에서 응원가를 힘차게 불렀다.", "사람들은 그를 불운한 천재라고 불렀다."],
        answer: 3,
        explanation: "'~라고 칭하다'의 의미로 쓰인 것은 4번입니다."
    }

];